### ISSUE TITLE
How to remind every 12:30 weekdays?

### ISSUE THREAD

**Issue by KarmaBlackshaw** [Mayerch1/RemindmeBot#1]
You're bot is the closest bot I can find which does the following. I hope you can help me with this, thank you!

**Comment by Mayerch1** [comment]
You can use two different ways.

1. Use the natural language parsing `every weekday at 12:30pm`

2. Directly by using the `rrule` format. 
    Create a reminder (e.g. `15 min`), then press `Set Interval` and add a new repeating rule. 
    Next enter `FREQ=WEEKLY;INTERVAL=1;WKST=MO;BYDAY=MO,TU,WE,TH,FR;BYHOUR=12;BYMINUTE=30`

**Comment by KarmaBlackshaw** [comment]
Thank you @Mayerch1!
