### ISSUE TITLE
DIscord RemindMe cannot see rfeminder created by someone else

### ISSUE THREAD

**Issue by plug-it-in** [Mayerch1/RemindmeBot#12]
So I have inherited Admin on a discord server wne the person who set up RemindMe has left. There is a reminder running and I cannot list or find it anywhere.  the /reminder_list command bring up this 

Given in your server timezone
|--------------------------------|
| No. | Next | Channel | Message |
|-----|------|---------|---------|
|-----|------|---------|---------|

Yet every day we see reminders generated in a specific channel.

How do I get to the reminderme job that does this?

**Comment by Mayerch1** [comment]
Do you have a role with administrator privileges for that server?

You must put the bot into `community mode` and designate yourself as moderator for the bot.
This way you can delete reminders created by other users

**Comment by plug-it-in** [comment]
Thx
