### ISSUE TITLE
Snooze buttons on reminder

### ISSUE THREAD

**Issue by mikeseese** [Mayerch1/RemindmeBot#2]
It would be great if there snooze buttons underneath reminders to snooze them:

![image](https://user-images.githubusercontent.com/549323/179829456-72a0e188-c9ff-483e-9e94-45c311bd22f5.png)

This could just create another non-recurring reminder with the same contents. You should be able to snooze nonrecurring and recurring reminders. Use case for recurring would be "I have a reminder that recurs every month to do a task. When the reminder comes, I'm busy, so I want to snooze it 20 minutes to remind me again to do it that day. It shouldn't affect my normal interval."

There could be a button for each the values Slack has: 20 minutes, 1 hour, 3 hours, Tomorrow, Next Week. Slack uses your "working hours" to determine what time to set it for tomorrow or next week, but it could just use 8AM since Discord doesn't even have a value for this. Next Week would be on the next Monday.

**Comment by Mayerch1** [comment]
The feature got implemented a while ago (in September already).
But I forgot to update this issue

![grafik](https://user-images.githubusercontent.com/28509096/218287656-0fcee94f-d776-4e21-bcee-c5d0e858fb11.png)
