### ISSUE TITLE
After creation message should be private

### ISSUE THREAD

**Issue by cdmichaelb** [Mayerch1/RemindmeBot#8]
![image](https://user-images.githubusercontent.com/1451709/214787065-00660173-c265-41bf-8216-2fadce658d39.png)
This page should be private to the creator. Anyone can delete or edit anyone's reminders.

**Comment by Mayerch1** [comment]
You can achieve this by opening `/settings`
And then selecting `Only Show to author` as style option

![grafik](https://user-images.githubusercontent.com/28509096/217097892-0cc3255a-ef99-48d0-bd0a-aa483930e870.png)


Feel free to re-open the issue, if this isn't what you're looking for.
